dataset:
  fileroot: "../../../data/"
  filename: "ns_floating_sim_2d_no.800.h5"

training_params:
  learning_rate: 0.001
  learning_rate_final: 0.1
  n_epochs: 300
  batch_size: 960

model:
  in_features: 3
  out_features: 2
  n_units: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
  
recording_params:
  tb_writer_root: "./logs/"
  model_save_root: "./checkpoint/"