# This file is to store the configuration for ddpm
dataset:
  fileroot: "../../../data/"
  filename: "ns_random_64x64_T50"
  is_test: False
  reduced_batch_factor: 1
  reduced_time_factor: 1
  reduced_resolution_factor: 1

training_params:
  learning_rate: 0.0001
  n_epochs: 30
  batch_size: 32

model:
  generator:
    in_channels: 3
    out_channels: 3
    init_features: 32
  discriminator:
    in_channels: 5
    init_features: 32
    feature_mults: [1, 2, 4, 8]
  
recording_params:
  eval_interval: 5
  tb_writer_root: "./logs/"
  model_save_root: "./checkpoint/"