# This file is to store the configuration for ddpm
dataset:
  fileroot: "../../../data/"
  filename: "ns_floating_sim_2d-seed1.h5"

training_params:
  G_learning_rate: 0.0002
  D_learning_rate: 0.00002
  n_epochs: 100
  batch_size: 32
  lambda_GAN: 100

model:
  generator:
    in_channels: 2
    out_channels: 2
    init_features: 64
    activation: leaky_relu
  discriminator:
    in_channels: 4
    init_features: 64
    activation: leaky_relu
  
recording_params:
  eval_interval: 1
  tb_writer_root: "./logs/"
  model_save_root: "./checkpoint/"