dirname: ???    # where the data is stored
experiment: ???
mode: ???
pdeconfig:
  train:
    class_path: pde.NSFullSmoke2D
    init_args:
      tmax: 50.0
      skip_t: 0.0
      Lx: 16.0 
      Ly: 16.0  
      nt: 500
      nx: 64 
      ny: 64
      t_sample_rate: 10
      nu: 0.03 # viscosity
      buoyancy: 0.5 # bouyancy force in vertical direction
      n_samples: 1000
  
  test:
    class_path: pde.NSFullSmoke2D
    init_args:
      tmax: 50.0
      skip_t: 0.0
      Lx: 16.0 
      Ly: 16.0  
      nt: 500
      nx: 64 
      ny: 64
      t_sample_rate: 1
      nu: 0.03 # viscosity
      buoyancy: 0.5 # bouyancy force in vertical direction
      n_samples: 16
overwrite: True