dirname: ???    # where the data is stored
experiment: ???
mode: ???
pdeconfig:
  train:
    class_path: pde.NSPointSmoke2D
    init_args:
      tmax: 50.0
      skip_t: 0.1
      Lx: 16.0 
      Ly: 16.0  
      nt: 500
      nx: 64 
      ny: 64
      t_sample_rate: 5
      nu: 0.03 # viscosity
      buoyancy: 1.0 # bouyancy force in vertical direction
      source_coord: [[2.0, 3.0], [2.0, 4.0], [2.0, 5.0], [2.0, 6.0], [2.0, 7.0], 
                     [3.0, 3.0], [3.0, 4.0], [3.0, 5.0], [3.0, 6.0], [3.0, 7.0], 
                     [4.0, 3.0], [4.0, 4.0], [4.0, 5.0], [4.0, 6.0], [4.0, 7.0], 
                     [5.0, 3.0], [5.0, 4.0], [5.0, 5.0], [5.0, 6.0], [5.0, 7.0], 
                     [6.0, 3.0], [6.0, 4.0], [6.0, 5.0], [6.0, 6.0], [6.0, 7.0], 
                     [7.0, 3.0], [7.0, 4.0], [7.0, 5.0], [7.0, 6.0], [7.0, 7.0], 
                     [8.0, 3.0], [8.0, 4.0], [8.0, 5.0], [8.0, 6.0], [8.0, 7.0], 
                     [9.0, 3.0], [9.0, 4.0], [9.0, 5.0], [9.0, 6.0], [9.0, 7.0], 
                     [10.0, 3.0], [10.0, 4.0], [10.0, 5.0], [10.0, 6.0], [10.0, 7.0], 
                     [11.0, 3.0], [11.0, 4.0], [11.0, 5.0], [11.0, 6.0], [11.0, 7.0], 
                     [12.0, 3.0], [12.0, 4.0], [12.0, 5.0], [12.0, 6.0], [12.0, 7.0], 
                     [13.0, 3.0], [13.0, 4.0], [13.0, 5.0], [13.0, 6.0], [13.0, 7.0]]
      source_strength: 1.0
      source_radius: 0.5
  
  test:
    class_path: pde.NSPointSmoke2D
    init_args:
      tmax: 50.0
      skip_t: 0.05
      Lx: 16.0  
      Ly: 16.0  # the physical size of y
      nt: 1000 # number of timesteps at minimum dt
      nx: 64 # spatial resolution on x-axis
      ny: 64 # spatial resolution on y-axis
      t_sample_rate: 5 # sampling rate of data as a multiple of minumum dt
      nu: 0.03 # viscosity
      buoyancy: 1.0 # bouyancy force in vertical direction
      source_coord: [[7.5, 3.0], [8.0, 5.5], [8.5, 6.5], [3.5, 3.5], [14.0, 2.5], [15.0, 9.0]]
      source_strength: 1.0
      source_radius: 0.5
overwrite: True